-- 코드를 입력하세요
WITH CTE AS
(
    SELECT HOST_ID
    FROM PLACES
    GROUP BY HOST_ID
    HAVING COUNT(ID) >= 2
)
SELECT P.ID, P.NAME, P.HOST_ID
FROM PLACES P RIGHT JOIN CTE C
ON P.HOST_ID = C.HOST_ID
ORDER BY 1;