-- 코드를 입력하세요
WITH CTE AS (
    SELECT MEMBER_ID, COUNT(*) AS CNT
   FROM REST_REVIEW
   GROUP BY MEMBER_ID
   ORDER BY CNT DESC
   LIMIT 1
)
SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE , '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW R LEFT JOIN MEMBER_PROFILE M
USING (MEMBER_ID)
WHERE MEMBER_ID IN (SELECT MEMBER_ID FROM CTE)
ORDER BY 3, 2 ASC;
