-- 대장균 개체의 ID(ID)와 자식의 수(CHILD_COUNT)를 출력하는 SQL 문을 작성해주세요. 자식이 없다면 자식의 수는 0으로 출력해주세요. 이때 결과는 개체의 ID 에 대해 오름차순 정렬해주세요.
WITH CTE_ID AS (
    SELECT ID 
    FROM ECOLI_DATA
),
CTE_COUNT AS (
    SELECT PARENT_ID, COUNT(ID) AS CNT
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
    GROUP BY PARENT_ID
)
SELECT 
    I.ID, 
    CASE WHEN C.CNT IS NULL THEN 0 ELSE C.CNT END AS CHILD_COUNT
FROM CTE_ID I LEFT JOIN CTE_COUNT C
ON I.ID = C.PARENT_ID
ORDER BY 1 ASC;