-- 코드를 입력하세요
SELECT CAR_ID, CAR_TYPE, FEE
FROM (SELECT *, ROUND(DAILY_FEE * (1 - PERCENT) * 30) AS FEE
      FROM CAR_RENTAL_COMPANY_CAR
      LEFT JOIN (SELECT CAR_TYPE, REPLACE(DISCOUNT_RATE, '%', '') / 100 AS PERCENT
                 FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
                WHERE DURATION_TYPE LIKE '30%') PLAN
      USING (CAR_TYPE)
      WHERE CAR_TYPE IN ('SUV', '세단')) CAR
WHERE CAR_ID NOT IN (SELECT CAR_ID
                    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                    WHERE START_DATE < '2022-11-01' AND END_DATE > '2022-11-30'
                    OR START_DATE BETWEEN '2022-11-01' AND '2022-11-30'
                    OR END_DATE BETWEEN '2022-11-01' AND '2022-11-30')
    AND FEE BETWEEN 500000 AND 1999999
ORDER BY 3 DESC, 2 ASC, 1 DESC;