-- 3세대의 대장균의 ID(ID) 를 출력하는 SQL 문을 작성해주세요. 이때 결과는 대장균의 ID 에 대해 오름차순 정렬해주세요.
SELECT T.ID
FROM ECOLI_DATA F 
LEFT JOIN ECOLI_DATA S ON F.ID = S.PARENT_ID
LEFT JOIN ECOLI_DATA T ON S.ID = T.PARENT_ID
WHERE F.PARENT_ID IS NULL 
AND T.ID IS NOT NULL
ORDER BY 1 ASC;