name: Daily README Update

on:
  push:
    paths:
      - 'Python3/**'
      - 'JavaScript/**'
      - 'Java/**'
      - 'MySQL/**'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set timezone
        run: sudo timedatectl set-timezone 'Asia/Seoul'

      - name: Update README.md
        run: |
          DATE=$(date '+%m-%d')

          LANGUAGES=("Python3" "JavaScript" "Java" "MySQL")
          STATUS=("❌" "❌" "❌" "❌")
          PROBLEM_NAME="-"
          PROBLEM_LINK="-"
          SQL_PROBLEM_NAME="-"
          SQL_PROBLEM_LINK="-"

          TODAY=$(date '+%Y년 %m월 %d일')

          idx=0
          for LANG in "${LANGUAGES[@]}"; do
            FILE=$(grep -rl "${TODAY}" "${LANG}" --include="README.md" | head -n 1)

            if [[ -n $FILE ]]; then
              STATUS[$idx]="✅"

              # 문제 이름 추출
              PROBLEM_NAME=$(head -n1 "$FILE" | sed 's/^# \[.*\] \(.*\) - .*/\1/')
              # 문제 링크 추출
              PROBLEM_LINK=$(grep -m1 -oP '(?<=\().*(?=\))' "$FILE")

              if [[ "$LANG" == "MySQL" ]]; then
                SQL_PROBLEM_NAME=$PROBLEM_NAME
                SQL_PROBLEM_LINK=$PROBLEM_LINK
              fi
            fi
            idx=$((idx + 1))
          done

          # README에 추가
          echo "| $DATE | ${STATUS[0]} | ${STATUS[1]} | ${STATUS[2]} | $PROBLEM_NAME | [문제 링크]($PROBLEM_LINK) | ${STATUS[3]} | $SQL_PROBLEM_NAME | [문제 링크]($SQL_PROBLEM_LINK) |" >> README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "docs: Daily README update ($DATE)" || echo "No changes to commit"
          git push
