name: Daily README Update

on:
  push:
    paths:
      - 'python/**'
      - 'javascript/**'
      - 'java/**'
      - 'sql/**'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set timezone
        run: sudo timedatectl set-timezone 'Asia/Seoul'

      - name: Update README.md
        run: |
          DATE=$(date '+%m-%d')

          PYTHON_STATUS="❌"
          JAVASCRIPT_STATUS="❌"
          JAVA_STATUS="❌"
          SQL_STATUS="❌"

          PYTHON_FILE=$(ls python | grep "$(date '+%Y%m%d')")
          JAVASCRIPT_FILE=$(ls javascript | grep "$(date '+%Y%m%d')")
          JAVA_FILE=$(ls java | grep "$(date '+%Y%m%d')")
          SQL_FILE=$(ls sql | grep "$(date '+%Y%m%d')")

          if [[ -n $PYTHON_FILE ]]; then PYTHON_STATUS="✅"; fi
          if [[ -n $JAVASCRIPT_FILE ]]; then JAVASCRIPT_STATUS="✅"; fi
          if [[ -n $JAVA_FILE ]]; then JAVA_STATUS="✅"; fi
          if [[ -n $SQL_FILE ]]; then SQL_STATUS="✅"; fi

          PROBLEM_NAME=$(echo "$PYTHON_FILE" | cut -d'_' -f2 | cut -d'.' -f1)
          PROBLEM_NUMBER=$(echo "$PYTHON_FILE" | cut -d'_' -f1)
          PROBLEM_LINK="[백준 ${PROBLEM_NUMBER}번](https://www.acmicpc.net/problem/${PROBLEM_NUMBER})"

          SQL_PROBLEM_NAME=$(echo "$SQL_FILE" | cut -d'_' -f2 | cut -d'.' -f1)
          SQL_PROBLEM_NUMBER=$(echo "$SQL_FILE" | cut -d'_' -f1)
          SQL_PROBLEM_LINK="[백준 ${SQL_PROBLEM_NUMBER}번](https://www.acmicpc.net/problem/${SQL_PROBLEM_NUMBER})"

          echo "| $DATE | $PYTHON_STATUS | $JAVASCRIPT_STATUS | $JAVA_STATUS | $PROBLEM_NAME | $PROBLEM_LINK | $SQL_STATUS | $SQL_PROBLEM_NAME | $SQL_PROBLEM_LINK |" >> README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "docs: Daily README update ($DATE)" || echo "No changes to commit"
          git push
