name: Daily README Update

on:
  push:
    paths:
      - 'Python3/**'
      - 'JavaScript/**'
      - 'Java/**'
      - 'MySQL/**'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set timezone
        run: sudo timedatectl set-timezone 'Asia/Seoul'

      - name: Update README.md
        run: |
          DATE=$(date '+%m-%d')

          PYTHON_STATUS="❌"
          JAVASCRIPT_STATUS="❌"
          JAVA_STATUS="❌"
          SQL_STATUS="❌"

          TODAY=$(date '+%Y년 %m월 %d일')

          # 공통 문제는 Python3에서만 찾기
          PYTHON_FILE=$(grep -rl "${TODAY}" "Python3" --include="README.md" | head -n 1)
          JAVASCRIPT_FILE=$(grep -rl "${TODAY}" "JavaScript" --include="README.md" | head -n 1)
          JAVA_FILE=$(grep -rl "${TODAY}" "Java" --include="README.md" | head -n 1)
          SQL_FILE=$(grep -rl "${TODAY}" "MySQL" --include="README.md" | head -n 1)

          if [[ -n $PYTHON_FILE ]]; then PYTHON_STATUS="✅"; fi
          if [[ -n $JAVASCRIPT_FILE ]]; then JAVASCRIPT_STATUS="✅"; fi
          if [[ -n $JAVA_FILE ]]; then JAVA_STATUS="✅"; fi
          if [[ -n $SQL_FILE ]]; then SQL_STATUS="✅"; fi

          # 공통 문제 정보 추출 (Python 기준)
          if [[ -n $PYTHON_FILE ]]; then
            COMMON_PROBLEM_NAME=$(head -n1 "$PYTHON_FILE" | sed 's/^# \[.*\] \(.*\) - .*/\1/')
            COMMON_PROBLEM_LINK=$(grep -m1 -oP '(?<=\().*(?=\))' "$PYTHON_FILE")
          else
            COMMON_PROBLEM_NAME="-"
            COMMON_PROBLEM_LINK="-"
          fi

          # SQL 문제 정보 별도 추출
          if [[ -n $SQL_FILE ]]; then
            SQL_PROBLEM_NAME=$(head -n1 "$SQL_FILE" | sed 's/^# \[.*\] \(.*\) - .*/\1/')
            SQL_PROBLEM_LINK=$(grep -m1 -oP '(?<=\().*(?=\))' "$SQL_FILE")
          else
            SQL_PROBLEM_NAME="-"
            SQL_PROBLEM_LINK="-"
          fi

          echo "| $DATE | $PYTHON_STATUS | $JAVASCRIPT_STATUS | $JAVA_STATUS | $COMMON_PROBLEM_NAME | [문제 링크]($COMMON_PROBLEM_LINK) | $SQL_STATUS | $SQL_PROBLEM_NAME | [문제 링크]($SQL_PROBLEM_LINK) |" >> README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "docs: Daily README update ($DATE)" || echo "No changes to commit"
          git push
