name: Daily README Update

on:
  push:
    paths:
      - 'Python/**'
      - 'Python3/**'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set timezone
        run: sudo timedatectl set-timezone 'Asia/Seoul'

      - name: Update README.md with Quoted Indentation
        run: |
          DATE=$(date '+%m/%d')

          PYTHON_STATUS="✕"

          TODAY=$(date '+%Y년 %m월 %d일')

          # 공통 문제 (Python 기준)
          PYTHON_FILE=$(grep -rl "${TODAY}" "Python3" --include="README.md" | head -n 1)

          if [[ -n $PYTHON_FILE ]]; then PYTHON_STATUS="✅"; fi

          # 공통 문제 정보 추출 (Python 기준)
          if [[ -n $PYTHON_FILE ]]; then
            COMMON_PROBLEM_NAME=$(head -n1 "$PYTHON_FILE" | sed 's/^# \[.*\] \(.*\) - .*/\1/')
            COMMON_PROBLEM_LINK=$(grep -m1 -oP '(?<=\().*(?=\))' "$PYTHON_FILE")
          else
            COMMON_PROBLEM_NAME="-"
            COMMON_PROBLEM_LINK="-"
          fi

          # README.md에 들여쓰기 추가 (인용문 방식)
          echo "> | $DATE | $PYTHON_STATUS | $COMMON_PROBLEM_NAME | [문제 링크]($COMMON_PROBLEM_LINK) |" >> README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "docs: Daily README update with quoted indentation ($DATE)" || echo "No changes to commit"
          git push
